export const UPDATE_FORM_INPUT_VALUES = "UPDATE_FORM_INPUT_VALUES";

export const SUBMIT_FORM_WITH_VALUES = "SUBMIT_FORM_WITH_VALUES";

export const POST_CARBON_USAGE = "POST_CARBON_USAGE";
export const POST_CARBON_USAGE_SUCCESS = "POST_CARBON_USAGE_SUCCES";
export const POST_CARBON_USAGE_FAILURE = "POST_CARBON_USAGE_FAILURE";

export const FILTER_BY_LOCATION = "FILTER_BY_LOCATION";
